specVersion: 0.2.0
name: app
version: 0.0.4
description: This project can be use as a starting po...
repository: https://github.com/subquery/subql-starter
schema:
  file: ./schema.graphql
network:
  genesisHash: '0xfc41b9bd8ef8fe53d58c7ea67c794c7ec9a73daf05e6d54b14ff6342c99ba64c'
  endpoint: wss://acala.polkawallet.io
  dictionary: https://api.subquery.network/sq/subquery/acala-dictionary
  chaintypes:
    file: './src/chain-types.js'
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:        
        - handler: handleLiquidateUnsafeCDP
          kind: substrate/EventHandler
          filter:
            module: cdpEngine
            method: LiquidateUnsafeCDP
        - handler: handlePositionUpdated
          kind: substrate/EventHandler
          filter:
            module: loans
            method: PositionUpdated